empleados_demo/empleados_demo/Controllers/PersonaController.cs
using empleados_demo.Entities;
using empleados_demo.Models.Operation;
using empleados_demo.Models.Operation.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace empleados_demo.Controllers
{
    public class PersonaController : Controller
    {
        private DatabaseContext dbContext = new DatabaseContext();      
        
        // GET: Persona
        public ActionResult Index()
        {
            var persons = dbContext.Personas;

            var result= (from per in persons
                    select new PersonaDTO
                    {
                        Id = per.Id,
                        Nombre = per.Nombre,
                        ApellidoP = per.ApellidoP,
                        FechaNacimiento = per.FechaNacimiento
                    }).ToList();

            return View(result);
        }
    }
}

empleados_demo/empleados_demo/Controllers/PuestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace empleados_demo.Controllers
{
    public class PuestoController : Controller
    {
        // GET: Puesto
        public ActionResult Index()
        {
            return View();
        }
    }
}

empleados_demo/empleados_demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adecco</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Personas", "Index", "Persona")</li>
                    <li>@Html.ActionLink("Puestos", "Index", "Puesto")</li>
                    <li>@Html.ActionLink("Empleados Puestos", "EmployeeJobs", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>